---
AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS CloudFormation template
Resources:

  S3BucketDataStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Sub ${AWS::StackName}
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - "*"
          AllowedMethods:
          - GET
          - PUT
          - POST
          - DELETE
          AllowedOrigins:
          - "*"
          ExposedHeaders:
          - Date
          Id: myCORSRuleId1
          MaxAge: '3600'

  S3BucketSite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Sub ${AWS::StackName}-site
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - "*"
          AllowedMethods:
          - GET
          AllowedOrigins:
          - "*"
          ExposedHeaders:
          - Date
          Id: myCORSRuleId1
          MaxAge: 3600

  S3BucketSitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketSite
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource:
            !Sub arn:aws:s3:::${S3BucketSite}/*
          Principal: "*"

  BucketUser:
    Type: AWS::IAM::User
    Properties:
      UserName:
        !Sub ${AWS::StackName}-user
      Path: "/"
      Policies:
      - PolicyName:
          !Sub ${AWS::StackName}-data-store
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:*
            Effect: Allow
            Resource:
              !Sub arn:aws:s3:::${S3BucketDataStore}*
      - PolicyName:
          !Sub ${AWS::StackName}-s3-site
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:*
            Effect: Allow
            Resource:
              !Sub arn:aws:s3:::${S3BucketSite}*

  BucketUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: BucketUser

Outputs:
  PublishUserAccessKeyId:
    Value:
      Ref: BucketUserAccessKey
    Description: The IAM AccessKeyId
  PublishUserSecretAccessKey:
    Value:
      Fn::GetAtt:
      - BucketUserAccessKey
      - SecretAccessKey
    Description: The IAM AccessSecretKey (shhhhhhh)
