#!/bin/bash

stack=in-browser-crypto
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

aws cloudformation create-stack \
  --stack-name $stack \
  --template-body file://$DIR/cloud.yaml \
  --capabilities CAPABILITY_IAM --capabilities CAPABILITY_NAMED_IAM && \

  aws cloudformation wait stack-create-complete \
    --stack-name $stack
